'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var axios = _interopDefault(require('axios'));
var moment = _interopDefault(require('moment'));

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
/* global Reflect, Promise */

var extendStatics = function(d, b) {
    extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return extendStatics(d, b);
};

function __extends(d, b) {
    extendStatics(d, b);
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
}

var __assign = function() {
    __assign = Object.assign || function __assign(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p)) t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};

var commonjsGlobal = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};

function unwrapExports (x) {
	return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, 'default') ? x.default : x;
}

function createCommonjsModule(fn, module) {
	return module = { exports: {} }, fn(module, module.exports), module.exports;
}

var lib = createCommonjsModule(function (module, exports) {

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var axios$$1 = _interopDefault(axios);
var moment$$1 = _interopDefault(moment);

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
/* global Reflect, Promise */

var extendStatics = function(d, b) {
    extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return extendStatics(d, b);
};

function __extends(d, b) {
    extendStatics(d, b);
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
}

var __assign = function() {
    __assign = Object.assign || function __assign(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p)) t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};

var commonjsGlobal$$1 = typeof window !== 'undefined' ? window : typeof commonjsGlobal !== 'undefined' ? commonjsGlobal : typeof self !== 'undefined' ? self : {};

function createCommonjsModule$$1(fn, module) {
	return module = { exports: {} }, fn(module, module.exports), module.exports;
}

var urlPattern = createCommonjsModule$$1(function (module, exports) {
// Generated by CoffeeScript 1.10.0
var slice = [].slice;

(function(root, factory) {
  if (exports !== null) {
    return module.exports = factory();
  } else {
    return root.UrlPattern = factory();
  }
})(commonjsGlobal$$1, function() {
  var P, UrlPattern, astNodeContainsSegmentsForProvidedParams, astNodeToNames, astNodeToRegexString, baseAstNodeToRegexString, concatMap, defaultOptions, escapeForRegex, getParam, keysAndValuesToObject, newParser, regexGroupCount, stringConcatMap, stringify;
  escapeForRegex = function(string) {
    return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
  };
  concatMap = function(array, f) {
    var i, length, results;
    results = [];
    i = -1;
    length = array.length;
    while (++i < length) {
      results = results.concat(f(array[i]));
    }
    return results;
  };
  stringConcatMap = function(array, f) {
    var i, length, result;
    result = '';
    i = -1;
    length = array.length;
    while (++i < length) {
      result += f(array[i]);
    }
    return result;
  };
  regexGroupCount = function(regex) {
    return (new RegExp(regex.toString() + '|')).exec('').length - 1;
  };
  keysAndValuesToObject = function(keys, values) {
    var i, key, length, object, value;
    object = {};
    i = -1;
    length = keys.length;
    while (++i < length) {
      key = keys[i];
      value = values[i];
      if (value == null) {
        continue;
      }
      if (object[key] != null) {
        if (!Array.isArray(object[key])) {
          object[key] = [object[key]];
        }
        object[key].push(value);
      } else {
        object[key] = value;
      }
    }
    return object;
  };
  P = {};
  P.Result = function(value, rest) {
    this.value = value;
    this.rest = rest;
  };
  P.Tagged = function(tag, value) {
    this.tag = tag;
    this.value = value;
  };
  P.tag = function(tag, parser) {
    return function(input) {
      var result, tagged;
      result = parser(input);
      if (result == null) {
        return;
      }
      tagged = new P.Tagged(tag, result.value);
      return new P.Result(tagged, result.rest);
    };
  };
  P.regex = function(regex) {
    return function(input) {
      var matches, result;
      matches = regex.exec(input);
      if (matches == null) {
        return;
      }
      result = matches[0];
      return new P.Result(result, input.slice(result.length));
    };
  };
  P.sequence = function() {
    var parsers;
    parsers = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return function(input) {
      var i, length, parser, rest, result, values;
      i = -1;
      length = parsers.length;
      values = [];
      rest = input;
      while (++i < length) {
        parser = parsers[i];
        result = parser(rest);
        if (result == null) {
          return;
        }
        values.push(result.value);
        rest = result.rest;
      }
      return new P.Result(values, rest);
    };
  };
  P.pick = function() {
    var indexes, parsers;
    indexes = arguments[0], parsers = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    return function(input) {
      var array, result;
      result = P.sequence.apply(P, parsers)(input);
      if (result == null) {
        return;
      }
      array = result.value;
      result.value = array[indexes];
      return result;
    };
  };
  P.string = function(string) {
    var length;
    length = string.length;
    return function(input) {
      if (input.slice(0, length) === string) {
        return new P.Result(string, input.slice(length));
      }
    };
  };
  P.lazy = function(fn) {
    var cached;
    cached = null;
    return function(input) {
      if (cached == null) {
        cached = fn();
      }
      return cached(input);
    };
  };
  P.baseMany = function(parser, end, stringResult, atLeastOneResultRequired, input) {
    var endResult, parserResult, rest, results;
    rest = input;
    results = stringResult ? '' : [];
    while (true) {
      if (end != null) {
        endResult = end(rest);
        if (endResult != null) {
          break;
        }
      }
      parserResult = parser(rest);
      if (parserResult == null) {
        break;
      }
      if (stringResult) {
        results += parserResult.value;
      } else {
        results.push(parserResult.value);
      }
      rest = parserResult.rest;
    }
    if (atLeastOneResultRequired && results.length === 0) {
      return;
    }
    return new P.Result(results, rest);
  };
  P.many1 = function(parser) {
    return function(input) {
      return P.baseMany(parser, null, false, true, input);
    };
  };
  P.concatMany1Till = function(parser, end) {
    return function(input) {
      return P.baseMany(parser, end, true, true, input);
    };
  };
  P.firstChoice = function() {
    var parsers;
    parsers = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return function(input) {
      var i, length, parser, result;
      i = -1;
      length = parsers.length;
      while (++i < length) {
        parser = parsers[i];
        result = parser(input);
        if (result != null) {
          return result;
        }
      }
    };
  };
  newParser = function(options) {
    var U;
    U = {};
    U.wildcard = P.tag('wildcard', P.string(options.wildcardChar));
    U.optional = P.tag('optional', P.pick(1, P.string(options.optionalSegmentStartChar), P.lazy(function() {
      return U.pattern;
    }), P.string(options.optionalSegmentEndChar)));
    U.name = P.regex(new RegExp("^[" + options.segmentNameCharset + "]+"));
    U.named = P.tag('named', P.pick(1, P.string(options.segmentNameStartChar), P.lazy(function() {
      return U.name;
    })));
    U.escapedChar = P.pick(1, P.string(options.escapeChar), P.regex(/^./));
    U["static"] = P.tag('static', P.concatMany1Till(P.firstChoice(P.lazy(function() {
      return U.escapedChar;
    }), P.regex(/^./)), P.firstChoice(P.string(options.segmentNameStartChar), P.string(options.optionalSegmentStartChar), P.string(options.optionalSegmentEndChar), U.wildcard)));
    U.token = P.lazy(function() {
      return P.firstChoice(U.wildcard, U.optional, U.named, U["static"]);
    });
    U.pattern = P.many1(P.lazy(function() {
      return U.token;
    }));
    return U;
  };
  defaultOptions = {
    escapeChar: '\\',
    segmentNameStartChar: ':',
    segmentValueCharset: 'a-zA-Z0-9-_~ %',
    segmentNameCharset: 'a-zA-Z0-9',
    optionalSegmentStartChar: '(',
    optionalSegmentEndChar: ')',
    wildcardChar: '*'
  };
  baseAstNodeToRegexString = function(astNode, segmentValueCharset) {
    if (Array.isArray(astNode)) {
      return stringConcatMap(astNode, function(node) {
        return baseAstNodeToRegexString(node, segmentValueCharset);
      });
    }
    switch (astNode.tag) {
      case 'wildcard':
        return '(.*?)';
      case 'named':
        return "([" + segmentValueCharset + "]+)";
      case 'static':
        return escapeForRegex(astNode.value);
      case 'optional':
        return '(?:' + baseAstNodeToRegexString(astNode.value, segmentValueCharset) + ')?';
    }
  };
  astNodeToRegexString = function(astNode, segmentValueCharset) {
    if (segmentValueCharset == null) {
      segmentValueCharset = defaultOptions.segmentValueCharset;
    }
    return '^' + baseAstNodeToRegexString(astNode, segmentValueCharset) + '$';
  };
  astNodeToNames = function(astNode) {
    if (Array.isArray(astNode)) {
      return concatMap(astNode, astNodeToNames);
    }
    switch (astNode.tag) {
      case 'wildcard':
        return ['_'];
      case 'named':
        return [astNode.value];
      case 'static':
        return [];
      case 'optional':
        return astNodeToNames(astNode.value);
    }
  };
  getParam = function(params, key, nextIndexes, sideEffects) {
    var index, maxIndex, result, value;
    if (sideEffects == null) {
      sideEffects = false;
    }
    value = params[key];
    if (value == null) {
      if (sideEffects) {
        throw new Error("no values provided for key `" + key + "`");
      } else {
        return;
      }
    }
    index = nextIndexes[key] || 0;
    maxIndex = Array.isArray(value) ? value.length - 1 : 0;
    if (index > maxIndex) {
      if (sideEffects) {
        throw new Error("too few values provided for key `" + key + "`");
      } else {
        return;
      }
    }
    result = Array.isArray(value) ? value[index] : value;
    if (sideEffects) {
      nextIndexes[key] = index + 1;
    }
    return result;
  };
  astNodeContainsSegmentsForProvidedParams = function(astNode, params, nextIndexes) {
    var i, length;
    if (Array.isArray(astNode)) {
      i = -1;
      length = astNode.length;
      while (++i < length) {
        if (astNodeContainsSegmentsForProvidedParams(astNode[i], params, nextIndexes)) {
          return true;
        }
      }
      return false;
    }
    switch (astNode.tag) {
      case 'wildcard':
        return getParam(params, '_', nextIndexes, false) != null;
      case 'named':
        return getParam(params, astNode.value, nextIndexes, false) != null;
      case 'static':
        return false;
      case 'optional':
        return astNodeContainsSegmentsForProvidedParams(astNode.value, params, nextIndexes);
    }
  };
  stringify = function(astNode, params, nextIndexes) {
    if (Array.isArray(astNode)) {
      return stringConcatMap(astNode, function(node) {
        return stringify(node, params, nextIndexes);
      });
    }
    switch (astNode.tag) {
      case 'wildcard':
        return getParam(params, '_', nextIndexes, true);
      case 'named':
        return getParam(params, astNode.value, nextIndexes, true);
      case 'static':
        return astNode.value;
      case 'optional':
        if (astNodeContainsSegmentsForProvidedParams(astNode.value, params, nextIndexes)) {
          return stringify(astNode.value, params, nextIndexes);
        } else {
          return '';
        }
    }
  };
  UrlPattern = function(arg1, arg2) {
    var groupCount, options, parsed, parser, withoutWhitespace;
    if (arg1 instanceof UrlPattern) {
      this.isRegex = arg1.isRegex;
      this.regex = arg1.regex;
      this.ast = arg1.ast;
      this.names = arg1.names;
      return;
    }
    this.isRegex = arg1 instanceof RegExp;
    if (!(('string' === typeof arg1) || this.isRegex)) {
      throw new TypeError('argument must be a regex or a string');
    }
    if (this.isRegex) {
      this.regex = arg1;
      if (arg2 != null) {
        if (!Array.isArray(arg2)) {
          throw new Error('if first argument is a regex the second argument may be an array of group names but you provided something else');
        }
        groupCount = regexGroupCount(this.regex);
        if (arg2.length !== groupCount) {
          throw new Error("regex contains " + groupCount + " groups but array of group names contains " + arg2.length);
        }
        this.names = arg2;
      }
      return;
    }
    if (arg1 === '') {
      throw new Error('argument must not be the empty string');
    }
    withoutWhitespace = arg1.replace(/\s+/g, '');
    if (withoutWhitespace !== arg1) {
      throw new Error('argument must not contain whitespace');
    }
    options = {
      escapeChar: (arg2 != null ? arg2.escapeChar : void 0) || defaultOptions.escapeChar,
      segmentNameStartChar: (arg2 != null ? arg2.segmentNameStartChar : void 0) || defaultOptions.segmentNameStartChar,
      segmentNameCharset: (arg2 != null ? arg2.segmentNameCharset : void 0) || defaultOptions.segmentNameCharset,
      segmentValueCharset: (arg2 != null ? arg2.segmentValueCharset : void 0) || defaultOptions.segmentValueCharset,
      optionalSegmentStartChar: (arg2 != null ? arg2.optionalSegmentStartChar : void 0) || defaultOptions.optionalSegmentStartChar,
      optionalSegmentEndChar: (arg2 != null ? arg2.optionalSegmentEndChar : void 0) || defaultOptions.optionalSegmentEndChar,
      wildcardChar: (arg2 != null ? arg2.wildcardChar : void 0) || defaultOptions.wildcardChar
    };
    parser = newParser(options);
    parsed = parser.pattern(arg1);
    if (parsed == null) {
      throw new Error("couldn't parse pattern");
    }
    if (parsed.rest !== '') {
      throw new Error("could only partially parse pattern");
    }
    this.ast = parsed.value;
    this.regex = new RegExp(astNodeToRegexString(this.ast, options.segmentValueCharset));
    this.names = astNodeToNames(this.ast);
  };
  UrlPattern.prototype.match = function(url) {
    var groups, match;
    match = this.regex.exec(url);
    if (match == null) {
      return null;
    }
    groups = match.slice(1);
    if (this.names) {
      return keysAndValuesToObject(this.names, groups);
    } else {
      return groups;
    }
  };
  UrlPattern.prototype.stringify = function(params) {
    if (params == null) {
      params = {};
    }
    if (this.isRegex) {
      throw new Error("can't stringify patterns generated from a regex");
    }
    if (params !== Object(params)) {
      throw new Error("argument must be an object or undefined");
    }
    return stringify(this.ast, params, {});
  };
  UrlPattern.escapeForRegex = escapeForRegex;
  UrlPattern.concatMap = concatMap;
  UrlPattern.stringConcatMap = stringConcatMap;
  UrlPattern.regexGroupCount = regexGroupCount;
  UrlPattern.keysAndValuesToObject = keysAndValuesToObject;
  UrlPattern.P = P;
  UrlPattern.newParser = newParser;
  UrlPattern.defaultOptions = defaultOptions;
  UrlPattern.astNodeToRegexString = astNodeToRegexString;
  UrlPattern.astNodeToNames = astNodeToNames;
  UrlPattern.getParam = getParam;
  UrlPattern.astNodeContainsSegmentsForProvidedParams = astNodeContainsSegmentsForProvidedParams;
  UrlPattern.stringify = stringify;
  return UrlPattern;
});
});

/**
 * Created by cuppi on 2016/12/14.
 */
/**
 * 网络地址工具类
 * @memberOf module:tool
 */
var UrlTool = /** @class */ (function () {
    function UrlTool() {
    }
    /**
     * 合成URL完整地址
     * @param {string} baseUrl 基础地址
     * @param {string} subUrl 相对地址
     * @param {string} parameters 参数
     * @returns {string} 返回拼接后的地址
     */
    UrlTool.urlFromPortion = function (baseUrl, subUrl, parameters) {
        if (!parameters) {
            parameters = {};
        }
        var paras = [];
        for (var key in parameters) {
            if (!parameters.hasOwnProperty(key)) {
                continue;
            }
            if (parameters[key] !== undefined) {
                paras.push(key + '=' + parameters[key]);
            }
        }
        var iUrl = baseUrl + subUrl;
        if (paras.length > 0) {
            iUrl = iUrl + '?' + paras.join('&');
        }
        return iUrl;
    };
    /**
     * 分析Url并解析为对象结构
     * @param url 待分析Url
     * @param options 分析Url配置
     * @return Promise<object> 参数为解析后的结果，url无效时返回Null
     */
    UrlTool.portionFromUrl = function (url, options) {
        options = __assign({ complete: false }, options);
        try {
            var urlObj = null;
            try {
                urlObj = new URL(url);
            }
            catch (e) {
                return null;
            }
            if (urlObj) {
                var _getKV = function (obj) {
                    var queryMap = {};
                    if (obj) {
                        for (var _i = 0, _a = obj.split('&'); _i < _a.length; _i++) {
                            var kv = _a[_i];
                            var kv_l = kv.split('=');
                            if (kv_l.length < 2)
                                continue;
                            queryMap[kv_l[0]] = kv_l[1];
                        }
                    }
                    return queryMap;
                };
                var query = new urlPattern(/^\??(.*)$/, ['query']).match(urlObj.search).query;
                var queryMap = _getKV(query);
                var hashObj = new urlPattern(/^#?(([\w-]*(\/)?)+)?((\?)+(.*))?$/, ['hashpath', '', '', 'hashsearch', '', '_hashsearch']).match(urlObj.hash);
                var hashMap = _getKV(hashObj._hashsearch);
                var p = {
                    host: urlObj.host,
                    href: urlObj.href,
                    pathname: urlObj.pathname,
                    protocol: urlObj.protocol,
                    query: queryMap,
                    hashpath: hashObj.hashpath,
                    hashquery: hashMap
                };
                if (options.complete) {
                    p = __assign({}, p, { origin: urlObj.origin, hostname: urlObj.hostname, port: urlObj.port, search: urlObj.search, username: urlObj.username, password: urlObj.password, hashsearch: hashObj.hashsearch, hash: urlObj.hash });
                }
                return p;
            }
            else {
                return null;
            }
        }
        catch (e) {
            throw e;
        }
    };
    return UrlTool;
}());

var DEFAULT_DELEGATE = {
    globalParams: function () { },
    globalHeaders: function () { },
    globalBodyData: function () { },
    requestInterceptor: function (config) {
        // Do something before request is sent
        console.log(config.method + "  " + UrlTool.urlFromPortion(config.url, '', config.params));
        return config;
    },
    requestInterceptorError: function (error) {
        // Do something with request error
        return Promise.reject(error);
    },
    responseInterceptor: function (response) {
        // Do something with response data
        return response;
    },
    responseInterceptorError: function (error) {
        // Do something with response error
        return Promise.reject(error);
    },
    resolveInterceptor: function (response, data) {
        return true;
    },
    rejectInterceptor: function (response, error) {
        return true;
    },
    responseDataInterceptor: function (data, response) {
        return data;
    },
    responseErrorInterceptor: function (error, response) {
        return error;
    }
};

/**
 * Created by cuppi on 2017/9/4.
 */
var CancelPromiseFactory = /** @class */ (function () {
    function CancelPromiseFactory(args) {
        return __assign({}, new Promise(args), { terminate: function () { } });
    }
    CancelPromiseFactory.createJPromise = function (para) {
        var promise = null;
        if (typeof para == "function") {
            promise = new Promise(para);
        }
        else {
            promise = para;
        }
        var hasCanceled_ = false;
        var wrappedPromise = new Promise(function (resolve, reject) {
            promise.then(function (val) { return hasCanceled_
                ? function () {
                }
                : resolve(val); }, function () {
                // 不写会有警告
            });
            promise.catch(function (error) { return hasCanceled_
                ? function () {
                }
                : reject(error); });
        });
        wrappedPromise.terminate = function () {
            hasCanceled_ = true;
        };
        return wrappedPromise;
    };
    return CancelPromiseFactory;
}());

/**
 * Created by cuppi on 2017/5/10.
 */
/**
 * 对象工具类
 * @memberOf module:tool
 */
var ObjectTool = /** @class */ (function () {
    function ObjectTool() {
    }
    /**
     * 删除对象某个属性
     * @param {object} target 对象
     * @param {string} propertyKey 属性
     * @returns {boolean} 是否删除成功
     */
    ObjectTool.deleteProperty = function (target, propertyKey) {
        if (target) {
            return Reflect.deleteProperty(target, propertyKey);
        }
        return true;
    };
    /**
     * 安全的获取链式属性 eg: a.b.c.d
     * @param target 目标对象
     * @param pChain 对象链式属性
     * @returns {*}
     */
    ObjectTool.safeGet = function (target) {
        var pChain = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            pChain[_i - 1] = arguments[_i];
        }
        if (!target || !pChain || pChain.length <= 0) {
            return undefined;
        }
        var property = target;
        var chainIndex = 0;
        do {
            property = property[pChain[chainIndex++]];
        } while (property && (chainIndex < pChain.length));
        return chainIndex === pChain.length ? property : undefined;
    };
    ObjectTool.isEmptyObject = function (obj) {
        return Object.keys(obj).length === 0 && obj.constructor === Object;
    };
    ObjectTool.getObjOrFuncResult = function (obj) {
        var o = null;
        if (obj) {
            if (typeof obj == "function") {
                o = obj();
            }
            if (typeof obj == "object") {
                o = obj;
            }
        }
        return o || {};
    };
    return ObjectTool;
}());

var REQUESTER_COUNT = 0;
var JRequester = /** @class */ (function () {
    function JRequester(method, baseUrl, url, parameters, headers, otherObject, delegate) {
        this.method = method;
        this.baseUrl = baseUrl;
        this.url = url;
        this.parameters = parameters;
        this.headers = headers;
        this.otherObject = otherObject;
        this.delegate = delegate;
        this.requesterId = ++REQUESTER_COUNT;
    }
    /**
     * 包裹可取消的请求 （使用fetch请求时使用，目前通过axios请求，无需使用）
     * @private
     * @param promise 异步请求块
     * @returns {Promise} 被包裹后的异步请求块
     */
    JRequester.wrapCancelablePromise = function (promise) {
        return CancelPromiseFactory.createJPromise(promise);
    };
    /**
     * 发送请求
     * @param method 方法类型
     * @param baseUrl 基地址
     * @param url 相对地址
     * @param parameters 参数
     * @param data data参数
     * @param headers 头参数
     * @param otherObject 其他相关设置
     * @param delegate 网络请求代理
     * @returns {CancelPromiseFactory<any>}
     */
    JRequester.create = function (method, baseUrl, url, parameters, data, headers, otherObject, delegate) {
        var requester = new JRequester(method, baseUrl, url, parameters, headers, otherObject, delegate);
        if (ObjectTool.isEmptyObject(data)) {
            data = null;
        }
        var jaxios = axios$$1.create(__assign({ method: method, params: parameters, baseURL: baseUrl, data: data, headers: headers }, otherObject));
        delegate = __assign({}, DEFAULT_DELEGATE, (delegate || {}));
        requester.jaxios = jaxios;
        jaxios.interceptors.request.use(function (config) {
            config.params = __assign({}, parameters);
            config.headers = __assign({}, headers);
            return delegate ? delegate.requestInterceptor(config) : config;
        }, function (error) {
            return delegate ? delegate.requestInterceptorError(error) : error;
        });
        jaxios.interceptors.response.use(function (response) {
            return delegate ? delegate.responseInterceptor(response) : response;
        }, function (error) {
            return delegate ? delegate.responseInterceptorError(error) : error;
        });
        return requester;
    };
    JRequester.prototype.request = function () {
        var _this = this;
        return CancelPromiseFactory.createJPromise(function (resolve, reject) {
            _this.jaxios.request({ url: _this.url }).then(function (response) {
                resolve(response);
            }, function (error) {
                reject(error);
            });
        });
    };
    JRequester.prototype.repeat = function () {
        var _this = this;
        return CancelPromiseFactory.createJPromise(function (resolve, reject) {
            _this.jaxios.request({ url: _this.url }).then(function (response) {
                resolve(response);
            }, function (error) {
                reject(error);
            });
        });
    };
    return JRequester;
}());

var DEFAULT_CONFIG = {
    baseUrl: '',
    delegate: DEFAULT_DELEGATE,
    carryParams: {},
    carryHeaders: {},
    carryBodyData: {},
    axiosConfig: {
        timeout: 10 * 1000
    }
};

/**
 * @private
 */
var Jpara = /** @class */ (function () {
    function Jpara() {
        var paras = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            paras[_i] = arguments[_i];
        }
        this._paras = [];
        for (var _a = 0, paras_1 = paras; _a < paras_1.length; _a++) {
            var para = paras_1[_a];
            this._paras.push(para);
        }
        this.isJpara = true;
    }
    Jpara.prototype.items = function () {
        return this._paras;
    };
    Jpara.emptyPara = function () {
        return new Jpara();
    };
    return Jpara;
}());
/**
 * 辅助任务类
 * @private
 */
var Jtask = /** @class */ (function () {
    function Jtask(task, parasPicker, resolve, reject) {
        this._task = task;
        this._resolve = resolve;
        this._reject = reject;
        this._parasPicker = parasPicker;
    }
    Jtask.prototype.setNextTask = function (task) {
        this._nextTask = task;
    };
    Jtask.prototype.do = function (paras) {
        var _this = this;
        paras = paras ? paras : this._parasPicker();
        this._task.apply(this, this.paraItems(paras)).then(function (data) {
            var nextPara = _this._resolve.apply(_this, [data].concat(_this.paraItems(paras)));
            if (_this._nextTask) {
                _this._nextTask.do(nextPara);
            }
        }, function (error) {
            if (_this._reject) {
                _this._reject.apply(_this, [error].concat(_this.paraItems(paras)));
            }
            else {
                console.log('ERROR: Don\'t find the error handler for task (' + _this._task.name + ')');
            }
        });
    };
    Jtask.prototype.paraItems = function (nextPara) {
        if (nextPara && nextPara.isJpara) {
            return nextPara.items();
        }
        return Jpara.emptyPara().items();
    };
    return Jtask;
}());
/**
 *
 * 任务连接类
 * @private
 */
var Jlink = /** @class */ (function () {
    function Jlink() {
        var tasks = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            tasks[_i] = arguments[_i];
        }
        this._tasks = [];
        for (var _a = 0, tasks_1 = tasks; _a < tasks_1.length; _a++) {
            var task = tasks_1[_a];
            this._tasks.push(task);
        }
        this._taskIndex = 0;
    }
    Jlink.prototype.para = function (para) {
        this._headTaskPara = para;
        return this;
    };
    Jlink.prototype.paras = function () {
        var paras = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            paras[_i] = arguments[_i];
        }
        this._allTaskPara = paras;
        return this;
    };
    Jlink.prototype.next = function (resolve, reject) {
        if (this._taskIndex >= this._tasks.length) {
            return this;
        }
        var nextTask = new Jtask(this._tasks[this._taskIndex], this._parasPicker(this._taskIndex), resolve, reject);
        this._taskIndex++;
        if (this._nextTask) {
            this._nextTask.setNextTask(nextTask);
        }
        else {
            this._headTask = nextTask;
        }
        this._nextTask = nextTask;
        return this;
    };
    Jlink.prototype.run = function () {
        this._headTask.do(this._parasPicker(0)());
        return this;
    };
    /**
     * 指定任务的paras的获取者 (目前实现会浪费内存，多个相同函数推入函数栈，后期优化）
     * @returns {Array}
     * @private
     */
    Jlink.prototype._parasPicker = function (index) {
        var _this = this;
        return function () {
            if (_this._allTaskPara && _this._allTaskPara.length > index) {
                return _this._allTaskPara[index];
            }
            if (index === 0 && _this._headTaskPara) {
                return _this._headTaskPara;
            }
            return Jpara.emptyPara();
        };
    };
    return Jlink;
}());
// let pro1 = () => {
//     return new Promise()
// };
//
// let pro2 = () => {
//     return new Promise
// };
// let l = jlink(pro1, pro2).next(
//     (data) => {
//         console.log(data);
//     },
//     error => {
//         console.log(error);
//     }).next(
//     (data) => {
//         console.log(data);
//     },
//     error => {
//         console.log(error);
//     }
// ).run();
/**
 * 任务组合类
 * @private
 */
// class Jcombine {
//   _tasks: Function[];
//   _headTaskPara: object;
//   _taskIndex: number;
//   _parasPicker: Function;
//   _headTask: Jtask;
//
//   constructor(...tasks) {
//     this._tasks = [];
//     for (var task of tasks) {
//       this._tasks.push(task);
//     }
//     this._taskIndex = 0;
//   }
//
//   para(para) {
//     this._headTaskPara = para;
//     return this;
//   }
//
//   paras(...paras) {
//     this._allTaskPara = paras;
//     return this;
//   }
//
//   next(resolve, reject) {
//     if (this._taskIndex >= this._tasks.length) {
//       return this;
//     }
//     let nextTask = new Jtask(this._tasks[this._taskIndex], this._parasPicker(this._taskIndex), resolve, reject);
//     this._taskIndex++;
//     if (this._nextTask) {
//       this._nextTask.setNextTask(nextTask);
//     } else {
//       this._headTask = nextTask;
//     }
//     this._nextTask = nextTask;
//     return this;
//   }
//
//   run() {
//     this._headTask.do(this._parasPicker(0)());
//     return this;
//   }
// }
/**
 * 任务连接类
 * @alias other/jlink
 * @param tasks
 * @returns {Jlink}
 */
function jlink() {
    var tasks = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        tasks[_i] = arguments[_i];
    }
    return new (Jlink.bind.apply(Jlink, [void 0].concat(tasks)))();
}
/**
 * @private
 * @param paras
 * @returns {Jpara}
 */
function jpara() {
    var paras = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        paras[_i] = arguments[_i];
    }
    return new (Jpara.bind.apply(Jpara, [void 0].concat(paras)))();
}
/**
 * @alias other/jcombine
 * @param tasks
 * @returns {Jcombine}
 */
// function jcombine(...tasks) {
//   return new Jcombine(...tasks);
// }
/**
 *
 * @param {GlobalValueRegistry | ((delegate: INetworkDelegate) => GlobalValueRegistry)} x
 * @return {x is (delegate: INetworkDelegate) => GlobalValueRegistry}
 */
function isGlobalValueRegistry(x) {
    return typeof x === 'function';
}
function isGlobalValueRegistryObject(x) {
    return typeof x === 'object';
}
function isGlobalValueRegistryFunction(x) {
    return typeof x === 'function';
}
/**
 * 获取全局指定参数
 * @param extraValues 全局参数列表
 * @param delegate 全局代理
 * @param globalValueRegistryPicker 全局参数代理对象
 * @return {{}}
 */
function jgetGlobalValue(extraValues, delegate, globalValueRegistryPicker) {
    var jgetGlobalValueWithKey = function (key) {
        var otherValues = {};
        if (!globalValueRegistryPicker) {
            throw new Error('未找到全局参数，请确认是否设置global代理');
        }
        var globalValueRegistry;
        if (isGlobalValueRegistry(globalValueRegistryPicker)) {
            globalValueRegistry = globalValueRegistryPicker(delegate);
        }
        else {
            globalValueRegistry = globalValueRegistryPicker;
        }
        var globalParaFunc = null;
        if (isGlobalValueRegistryObject(globalValueRegistry)) {
            globalParaFunc = globalValueRegistry[key];
        }
        if (isGlobalValueRegistryFunction(globalValueRegistry)) {
            globalParaFunc = globalValueRegistry()[key];
        }
        if (globalParaFunc) {
            var globalPara = null;
            if (typeof globalParaFunc == "function") {
                globalPara = globalParaFunc();
            }
            else {
                globalPara = globalParaFunc;
            }
            if (typeof globalPara == "object") {
                otherValues = __assign({}, otherValues, globalPara);
            }
            else if (typeof globalPara === 'string' || typeof globalPara === 'number') {
                otherValues[key] = globalPara;
            }
            else {
                throw new Error("\u5168\u5C40\u53D8\u91CF\u7C7B\u578B\u4E0D\u6B63\u786E:" + key);
            }
        }
        else {
            throw new Error("\u4E0D\u5B58\u5728\u7684\u5168\u5C40\u53D8\u91CF:" + key);
        }
        return otherValues;
    };
    var globalOtherValues = {};
    extraValues.forEach(function (key) {
        if (typeof key == "object") {
            globalOtherValues = __assign({}, globalOtherValues, key);
        }
        else {
            if (!delegate)
                return;
            globalOtherValues = __assign({}, globalOtherValues, jgetGlobalValueWithKey(key));
        }
    });
    return globalOtherValues;
}

var JNetworkError = /** @class */ (function (_super) {
    __extends(JNetworkError, _super);
    function JNetworkError(errorMessage, code) {
        var _this = this;
        if (typeof errorMessage === 'string') {
            _this = _super.call(this, errorMessage) || this;
        }
        else if (errorMessage instanceof Error) {
            _this = _super.call(this, errorMessage.message) || this;
        }
        else {
            throw new Error('JNetworkError: 构造函数非法类型');
        }
        _this.errorCode = code;
        return _this;
        // Reflect.defineProperty(this, 'errorCode', {value: code});
    }
    return JNetworkError;
}(Error));

var JRequestEngine = /** @class */ (function () {
    // private readonly reactor;
    function JRequestEngine() {
        this.isRunning = false;
        this.runQueue = [];
        // let reactor = new Reactor();
        // this.reactor = reactor;
        // reactor.registerEvent('requestCanLoad');
    }
    JRequestEngine.prototype._pushRunQueue = function (request, resolve, reject) {
        this.runQueue.push({
            request: request,
            resolve: resolve,
            reject: reject
        });
    };
    JRequestEngine.prototype._popRunQueue = function () {
        return this.runQueue.shift();
    };
    JRequestEngine.prototype.addRequest = function (request) {
        var _this = this;
        return CancelPromiseFactory.createJPromise(function (resolve, reject) {
            if (!_this.isRunning) {
                _this.isRunning = true;
                _this.do(request, resolve, reject);
            }
            else {
                _this._pushRunQueue(request, resolve, reject);
            }
        });
    };
    JRequestEngine.prototype.do = function (request, resolve, reject) {
        var _this = this;
        request.request().then(function (data) {
            setTimeout(resolve(data), 0);
            var task = _this._popRunQueue();
            if (task) {
                _this.do(task.request, task.resolve, task.reject);
            }
            else {
                _this.isRunning = false;
            }
        }, function (error) {
            reject(error);
        });
    };
    return JRequestEngine;
}());

var JNetworkRoot = /** @class */ (function () {
    function JNetworkRoot() {
        this.extraParams = [];
        this.extraHeaders = [];
        this.extraBodyData = [];
    }
    JNetworkRoot.prototype.useParams = function () {
        var paras = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            paras[_i] = arguments[_i];
        }
        this.extraParams = paras;
        return this;
    };
    JNetworkRoot.prototype.useHeaders = function () {
        var headers = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            headers[_i] = arguments[_i];
        }
        this.extraHeaders = headers;
        return this;
    };
    JNetworkRoot.prototype.useBodyData = function () {
        var bodyData = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            bodyData[_i] = arguments[_i];
        }
        this.extraBodyData = bodyData;
        return this;
    };
    JNetworkRoot.prototype.clearExtraData = function () {
        this.extraParams = [];
        this.extraHeaders = [];
        this.extraBodyData = [];
    };
    return JNetworkRoot;
}());

var GROUP_COUNT = 0;
var JNetworkGroup = /** @class */ (function (_super) {
    __extends(JNetworkGroup, _super);
    function JNetworkGroup(baseUrl, axiosConfig, delegate, options) {
        var _this = _super.call(this) || this;
        _this.requestEngine = new JRequestEngine();
        _this.baseUrl = baseUrl;
        _this.axiosConfig = axiosConfig || {};
        _this.delegate = delegate || null;
        _this.groupId = ++GROUP_COUNT;
        if (options) {
            _this.freezeParams = options.freezeParams || [];
            _this.freezeHeaders = options.freezeHeaders || [];
            _this.freezeBodyData = options.freezeBodyData || [];
            _this.freezeCarryParams = options.freezeCarryParams || {};
            _this.freezeCarryHeaders = options.freezeCarryHeaders || {};
            _this.freezeCarryBodyData = options.freezeCarryBodyData || {};
            _this.isSync = options.isSync;
        }
        return _this;
    }
    JNetworkGroup.prototype.pickInjectParams = function () {
        return __assign({}, ObjectTool.getObjOrFuncResult(this.freezeCarryParams), jgetGlobalValue(this.freezeParams.concat(this.extraParams), this.delegate, function (_) { return _.globalParams; }));
    };
    JNetworkGroup.prototype.pickInjectHeaders = function () {
        return __assign({}, ObjectTool.getObjOrFuncResult(this.freezeCarryHeaders), jgetGlobalValue(this.freezeHeaders.concat(this.extraHeaders), this.delegate, function (_) { return _.globalHeaders; }));
    };
    JNetworkGroup.prototype.pickInjectBodyData = function () {
        return __assign({}, ObjectTool.getObjOrFuncResult(this.freezeCarryBodyData), jgetGlobalValue(this.freezeBodyData.concat(this.extraBodyData), this.delegate, function (_) { return _.globalBodyData; }));
    };
    /**
     * 发送请求
     * @param method 方法类型
     * @param baseUrl 基地址
     * @param url 相对地址
     * @param parameters 参数
     * @param data data参数
     * @param headers 头参数
     * @param otherObject 其他相关设置
     * @returns {CancelPromiseFactory<any>}
     */
    JNetworkGroup.prototype.fetchRequest = function (method, baseUrl, url, parameters, data, headers, otherObject) {
        var carryParams = ObjectTool.getObjOrFuncResult(this.freezeCarryParams);
        var carryHeaders = ObjectTool.getObjOrFuncResult(this.freezeHeaders);
        var carryBodyData = ObjectTool.getObjOrFuncResult(this.freezeCarryBodyData);
        this.clearExtraData();
        var delegate = this.delegate;
        var globalOtherParams = this.pickInjectParams();
        var globalOtherHeaders = this.pickInjectHeaders();
        var globalOtherBodyData = this.pickInjectBodyData();
        var request = JRequester.create(method, baseUrl, url, __assign({}, carryParams, globalOtherParams, parameters), __assign({}, carryBodyData, globalOtherBodyData, data), __assign({ 'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded' }, carryHeaders, globalOtherHeaders, headers), __assign({ axiosConfig: this.axiosConfig }, otherObject), delegate);
        if (this.isSync) {
            return this.requestEngine.addRequest(request);
        }
        else {
            return CancelPromiseFactory.createJPromise(function (resolve, reject) {
                request.request().then(function (response) {
                    if (response.status === 200) {
                        resolve(response);
                    }
                    else {
                        reject(new JNetworkError(response.statusText, response.status));
                    }
                }).catch(function (error) {
                    reject(error);
                });
            });
        }
    };
    JNetworkGroup.prototype.freedomPOST = function (baseUrl, url, parameters, headers, otherObject) {
        return this.fetchRequest('post', baseUrl, url || '', parameters || {}, {}, headers || {}, otherObject || {});
    };
    JNetworkGroup.prototype.freedomGET = function (baseUrl, url, parameters, headers, otherObject) {
        return this.fetchRequest('get', baseUrl, url || '', parameters || {}, {}, headers || {}, otherObject || {});
    };
    JNetworkGroup.prototype.POST = function (url, parameters, headers, otherObject) {
        return this.freedomPOST(this.baseUrl, url, parameters, headers, __assign({}, this.axiosConfig, otherObject));
    };
    JNetworkGroup.prototype.GET = function (url, parameters, headers, otherObject) {
        return this.freedomGET(this.baseUrl, url, parameters, headers, __assign({}, this.axiosConfig, otherObject));
    };
    JNetworkGroup.prototype.freedomDataPOST = function (baseUrl, url, data, headers, otherObject) {
        return this.fetchRequest('post', baseUrl, url || '', {}, data || {}, headers || {}, otherObject || {});
    };
    JNetworkGroup.prototype.freedomDataGET = function (baseUrl, url, data, headers, otherObject) {
        return this.fetchRequest('get', baseUrl, url || '', {}, data || {}, headers || {}, otherObject || {});
    };
    JNetworkGroup.prototype.dataPOST = function (url, data, headers, otherObject) {
        return this.freedomDataPOST(this.baseUrl, url, data, headers, __assign({}, this.axiosConfig, otherObject));
    };
    JNetworkGroup.prototype.dataGET = function (url, data, headers, otherObject) {
        return this.freedomDataGET(this.baseUrl, url, data, headers, __assign({}, this.axiosConfig, otherObject));
    };
    return JNetworkGroup;
}(JNetworkRoot));

var INSTANCE_COUNT = 0;
/** @module network*/
/**
 * 网络请求类
 * @hideconstructor
 */
var JNetwork = /** @class */ (function (_super) {
    __extends(JNetwork, _super);
    function JNetwork(config) {
        if (config === void 0) { config = DEFAULT_CONFIG; }
        var _this = _super.call(this) || this;
        _this.config = DEFAULT_CONFIG;
        _this.groupList = [];
        config = __assign({}, DEFAULT_CONFIG, config);
        _this.baseUrl = config.baseUrl;
        _this.delegate = config.delegate || null;
        _this.carryParams = config.carryParams || {};
        _this.carryHeaders = config.carryHeaders || {};
        _this.carryBodyData = config.carryBodyData || {};
        _this.axiosConfig = config.axiosConfig || {
            timeout: 10 * 1000
        };
        _this.config = config;
        _this.instanceId = ++INSTANCE_COUNT;
        return _this;
    }
    JNetwork.useParams = function () {
        var paras = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            paras[_i] = arguments[_i];
        }
        var instance = this.defaultInstance();
        instance.extraParams = paras;
        return instance;
    };
    JNetwork.useHeaders = function () {
        var headers = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            headers[_i] = arguments[_i];
        }
        var instance = this.defaultInstance();
        instance.extraHeaders = headers;
        return instance;
    };
    JNetwork.useBodyData = function () {
        var bodyData = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            bodyData[_i] = arguments[_i];
        }
        var instance = this.defaultInstance();
        instance.extraBodyData = bodyData;
        return instance;
    };
    JNetwork.instance = function (config) {
        if (config === void 0) { config = DEFAULT_CONFIG; }
        return new JNetwork(config);
    };
    JNetwork.defaultInstance = function () {
        if (!this._instance) {
            this._instance = new JNetwork();
        }
        return this._instance;
    };
    JNetwork.prototype.pickInjectParams = function () {
        return __assign({}, ObjectTool.getObjOrFuncResult(this.carryParams), jgetGlobalValue(this.extraParams, this.delegate, function (_) { return _.globalParams; }));
    };
    JNetwork.prototype.pickInjectHeaders = function () {
        return __assign({}, ObjectTool.getObjOrFuncResult(this.carryHeaders), jgetGlobalValue(this.extraHeaders, this.delegate, function (_) { return _.globalHeaders; }));
    };
    JNetwork.prototype.pickInjectBodyData = function () {
        return __assign({}, ObjectTool.getObjOrFuncResult(this.carryBodyData), jgetGlobalValue(this.extraBodyData, this.delegate, function (_) { return _.globalBodyData; }));
    };
    JNetwork.prototype.createGroup = function (options) {
        options = __assign({
            notClearExtraData: false,
            isSync: false
        }, options);
        var group = new JNetworkGroup(this.baseUrl, this.axiosConfig, this.delegate, {
            freezeParams: this.extraParams,
            freezeHeaders: this.extraHeaders,
            freezeBodyData: this.extraBodyData,
            freezeCarryParams: ObjectTool.getObjOrFuncResult(this.carryParams),
            freezeCarryHeaders: ObjectTool.getObjOrFuncResult(this.carryHeaders),
            freezeCarryBodyData: ObjectTool.getObjOrFuncResult(this.carryBodyData),
            isSync: options.isSync
        });
        if (!options.notClearExtraData) {
            this.clearExtraData();
        }
        this.groupList.push(group);
        return group;
    };
    JNetwork.prototype.clearGroup = function () {
        // TODO: 冻结每组活动
        this.groupList.splice(0);
    };
    /**
     * 验证失败
     * @private
     * @returns {Promise}
     */
    JNetwork.failedAuthorizationNetwork = function () {
        return new Promise(function (resolve, reject) {
            reject(new Error('authorization error'));
        });
    };
    /**
     * 不存在的方法
     * @private
     * @returns {Promise}
     */
    JNetwork.unrealizedMethod = function () {
        return new Promise(function (resolve, reject) {
            reject(new Error('unrealized method'));
        });
    };
    /***
     * 检查是否配置SDK
     * @private
     */
    JNetwork.prototype.checkConfigBaseUrl = function () {
        if (!this.baseUrl || this.baseUrl === '') {
            console.log('please check if you have config baseUrl for SDK');
            // throw Error('Not Config');
        }
    };
    /**
     * 发送请求
     * @param method 方法类型
     * @param baseUrl 基地址
     * @param url 相对地址
     * @param parameters 参数
     * @param data data参数
     * @param headers 头参数
     * @param otherObject 其他相关设置
     * @returns {CancelPromiseFactory<any>}
     */
    JNetwork.prototype.fetchRequest = function (method, baseUrl, url, parameters, data, headers, otherObject) {
        var carryParams = ObjectTool.getObjOrFuncResult(this.carryParams);
        var carryHeaders = ObjectTool.getObjOrFuncResult(this.carryHeaders);
        var carryBodyData = ObjectTool.getObjOrFuncResult(this.carryBodyData);
        this.clearExtraData();
        var delegate = this.delegate;
        var globalOtherParams = this.pickInjectParams();
        var globalOtherHeaders = this.pickInjectHeaders();
        var globalOtherBodyData = this.pickInjectBodyData();
        var request = JRequester.create(method, baseUrl, url, __assign({}, carryParams, globalOtherParams, parameters), __assign({}, carryBodyData, globalOtherBodyData, data), __assign({ 'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded' }, carryHeaders, globalOtherHeaders, headers), __assign({}, this.axiosConfig, otherObject), delegate);
        return CancelPromiseFactory.createJPromise(function (resolve, reject) {
            request.request().then(function (response) {
                if (response.status === 200) {
                    resolve(response);
                }
                else {
                    reject(new JNetworkError(response.statusText, response.status));
                }
            }).catch(function (error) {
                reject(error);
            });
        });
    };
    /**
     * 高自由度POST方法
     * @param {string} baseUrl 基地址
     * @param {string} url 相对地址
     * @param {object} parameters 地址参数
     * @param {object} headers 头参数
     * @param {object} otherObject 其他可用配置
     * @returns {Promise} 异步请求块
     */
    JNetwork.freedomPOST = function (baseUrl, url, parameters, headers, otherObject) {
        return this.defaultInstance().freedomPOST(baseUrl, url, parameters, headers, otherObject);
    };
    /**
     * 高自由度GET方法
     * @param {string} baseUrl
     * @param {string} url
     * @param {object} parameters
     * @param {object} headers
     * @param {object} otherObject
     * @returns {Promise} 异步请求块
     */
    JNetwork.freedomGET = function (baseUrl, url, parameters, headers, otherObject) {
        return this.defaultInstance().freedomGET(baseUrl, url, parameters, headers, otherObject);
    };
    JNetwork.prototype.freedomPOST = function (baseUrl, url, parameters, headers, otherObject) {
        return this.fetchRequest('post', baseUrl, url || '', parameters || {}, {}, headers || {}, otherObject || {});
    };
    JNetwork.prototype.freedomGET = function (baseUrl, url, parameters, headers, otherObject) {
        return this.fetchRequest('get', baseUrl, url || '', parameters || {}, {}, headers || {}, otherObject || {});
    };
    JNetwork.prototype.POST = function (url, parameters, headers, otherObject) {
        return this.freedomPOST(this.baseUrl, url, parameters, headers, __assign({}, this.axiosConfig, otherObject));
    };
    JNetwork.prototype.GET = function (url, parameters, headers, otherObject) {
        return this.freedomGET(this.baseUrl, url, parameters, headers, __assign({}, this.axiosConfig, otherObject));
    };
    JNetwork.prototype.freedomDataPOST = function (baseUrl, url, data, headers, otherObject) {
        return this.fetchRequest('post', baseUrl, url || '', {}, data || {}, headers || {}, otherObject || {});
    };
    JNetwork.prototype.freedomDataGET = function (baseUrl, url, data, headers, otherObject) {
        return this.fetchRequest('get', baseUrl, url || '', {}, data || {}, headers || {}, otherObject || {});
    };
    JNetwork.prototype.dataPOST = function (url, data, headers, otherObject) {
        return this.freedomDataPOST(this.baseUrl, url, data, headers, __assign({}, this.axiosConfig, otherObject));
    };
    JNetwork.prototype.dataGET = function (url, data, headers, otherObject) {
        return this.freedomDataGET(this.baseUrl, url, data, headers, __assign({}, this.axiosConfig, otherObject));
    };
    return JNetwork;
}(JNetworkRoot));

/**
 * Created by cuppi on 2016/11/25.
 */
// 北京时区(东八区)早于协调世界时
// const STANDARD_TIMEZONE = -480;
var STANDARD_TIMEZONE = 480;
var _date_format_shim = function (f) {
    if (f) {
        f = f.replace('yyyy', 'YYYY');
        f = f.replace('dd', 'DD');
        f = f.replace('hh', 'HH');
    }
    return f;
};
var _ti2d = function (ti) {
    return moment$$1(ti * 1000).toDate();
};
var _d2ti = function (d) {
    return moment$$1(d).unix();
};
var _ti2ds = function (ti, f) {
    f = _date_format_shim(f);
    return moment$$1(ti * 1000).utcOffset(STANDARD_TIMEZONE).format(f);
};
var _ds2ti = function (ds, z) {
    return DateTool.timeIntervalFromDate(moment$$1(ds).utcOffset(z, true).toDate());
};
var _d2ds = function (d, f) {
    f = _date_format_shim(f);
    return moment$$1(d).utcOffset(STANDARD_TIMEZONE).format(f);
};
var _ds2d = function (ds, z) {
    return moment$$1(ds).utcOffset(z, true).toDate();
};
/**
 * 时间工具类
 * @memberOf module:tool
 */
var DateTool = /** @class */ (function () {
    function DateTool() {
    }
    // 距离标准时区(STANDARD_TIMEZONE)的位移 --单位为分钟
    DateTool.offsetFromStandardTimezone = function () {
        return new Date().getTimezoneOffset();
    };
    /**
     * 当前日期是什么类型
     * @param {Date | string | number} _ 日期
     * @private
     * @returns {string}
     */
    DateTool.whatType = function (_) {
        if (_ instanceof Date) {
            return 'Date';
        }
        return typeof (_);
    };
    /**
     * 这个日期要做什么
     * @param {Date | string | number} _ 日期
     * @param {Function} dateDoing 日期格式做的事情
     * @param {Function} strDoing 字符串格式做的事情
     * @param {Function} numDoing 数字格式做的事情
     * @param {Function} otherDoing  其他格式做的事情
     * @private
     */
    DateTool.whatTypeDoing = function (_, dateDoing, strDoing, numDoing, otherDoing) {
        if (typeof (_) === 'string') {
            strDoing();
        }
        if (typeof (_) === 'number') {
            numDoing();
        }
        if (_ instanceof Date) {
            dateDoing();
        }
        if (otherDoing) {
            otherDoing();
        }
    };
    /**
     * 想要日期格式的日期
     * @param {Date | string | number} _ 日期
     * @returns {Date}
     */
    DateTool.wantDate = function (_) {
        var result = null;
        DateTool.whatTypeDoing(_, function () {
            result = _;
        }, function () {
            result = DateTool.dateFromDateString(_);
        }, function () {
            result = DateTool.dateFromTimeInterval(_);
        });
        return result;
    };
    /**
     * 想要时间戳格式的日期
     * @param {Date | string | number} _ 日期
     * @returns {number}
     */
    DateTool.wantTimeInterval = function (_) {
        var result = null;
        DateTool.whatTypeDoing(_, function () {
            result = DateTool.timeIntervalFromDate(_);
        }, function () {
            result = DateTool.timeIntervalFromDateString(_);
        }, function () {
            result = _;
        });
        return result;
    };
    /**
     * 日期转换时间戳
     * @static
     * @param {Date} date 日期
     * @returns {number} 时间戳
     */
    DateTool.timeIntervalFromDate = function (date) {
        return _d2ti(date);
    };
    /**
     * 时间戳转换日期
     * @param {number} timeInterval 时间戳
     * @returns {Date} 日期
     */
    DateTool.dateFromTimeInterval = function (timeInterval) {
        return _ti2d(timeInterval);
    };
    /**
     * 日期字符串转换时间戳
     * @param {string} dateString 日期
     * @param {string} timezone 时区
     * @returns {number} 时间戳
     */
    DateTool.timeIntervalFromDateString = function (dateString, timezone) {
        if (timezone === void 0) { timezone = STANDARD_TIMEZONE; }
        return _ds2ti(dateString, timezone);
    };
    /**
     * 时间戳转换日期字符串
     * @param {number} timeInterval 时间戳
     * @param {string} format 日期格式 如: YYYY-MM-DD HH:mm:ss
     * @returns {string} 日期字符串
     */
    DateTool.dateStringFromTimeInterval = function (timeInterval, format) {
        if (format === void 0) { format = 'YYYY-MM-DD HH:mm:ss'; }
        return _ti2ds(timeInterval, format);
    };
    /**
     * 日期字符串转换日期 （待开发）
     * @param {string} dateString 日期字符串
     * @param {string} timezone 时区
     * @returns {Date} 日期
     */
    DateTool.dateFromDateString = function (dateString, timezone) {
        if (timezone === void 0) { timezone = STANDARD_TIMEZONE; }
        return _ds2d(dateString, timezone);
    };
    /**
     * 日期转换日期字符串
     * @param {Date} date Date对象
     * @param {string} format 格式化信息
     * @returns {string} 日期字符串
     */
    DateTool.dateStringFromDate = function (date, format) {
        if (format === void 0) { format = 'YYYY-MM-DD HH:mm:ss'; }
        return _d2ds(date, format);
    };
    /**
     * 获取当前日期对象
     * @returns {Date} 当前日期对象
     */
    DateTool.currentDate = function () {
        return moment$$1().utcOffset(STANDARD_TIMEZONE).toDate();
    };
    /**
     * 获取当前日期字符串
     * @param {string} format 字符串格式
     * @returns {string} 当前日期字符串
     */
    DateTool.currentDateString = function (format) {
        if (format === void 0) { format = 'YYYY-MM-DD HH:mm:ss'; }
        return _d2ds(DateTool.currentDate(), format);
    };
    /**
     * 获取当前时间戳
     * @returns {number} 当前时间戳
     */
    DateTool.currentTimeInterval = function () {
        return moment$$1().unix();
    };
    // TODO 需要优化月份的算法
    /**
     * 获取(多态)日期的距离
     * @param {Date | string | number} startDate 起始日期
     * @param {Date | string | number} endDate 结束日期
     * @param {boolean} justSeconds 只需要秒的总数
     * @returns {Array} [秒，分，小时，天，月, 年]
     */
    DateTool.distanceBetweenDate = function (startDate, endDate, justSeconds) {
        var startTimeInterval = this.wantTimeInterval(startDate);
        var endTimeInterval = this.wantTimeInterval(endDate);
        var distance = endTimeInterval - startTimeInterval;
        if (justSeconds) {
            return [distance, 0, 0, 0, 0];
        }
        var sec = distance % 60;
        distance = Math.floor(distance / 60);
        var min = distance % 60;
        distance = Math.floor(distance / 60);
        var hour = distance % 24;
        distance = Math.floor(distance / 24);
        var day = distance % 1000;
        var mou = Math.floor(distance / 1000);
        return [sec, min, hour, day, mou];
    };
    // TODO 待开发
    /**
     * 变换日期字符串格式 （待开发）
     * @since ~1.1.*
     * @param {string} dateString 日期字符串
     * @param {string} fromFormat 输入格式
     * @param {string} toFormat 输出格式
     * @param {string} timezone 时区
     * @returns {string} 字符串
     */
    DateTool.transformDateStringByFormat = function (dateString, fromFormat, toFormat, timezone) {
        if (toFormat === void 0) { toFormat = 'YYYY-MM-DD HH:mm:ss'; }
        if (timezone === void 0) { timezone = STANDARD_TIMEZONE; }
        return _d2ds(_ds2d(dateString, timezone), toFormat);
    };
    /**
     * 获取指定(多态)日期为星期几
     * @param {Date | string | number} date 日期
     * @returns {number} 0~6  星期一~星期日
     */
    DateTool.weekDay = function (date) {
        return (moment$$1(DateTool.wantDate(date)).utcOffset(STANDARD_TIMEZONE).day() + 6) % 7;
    };
    /**
     * 获取(多态)日期某天后的日期()
     * @param {Date | string | number} beganDate
     * @param {number} days
     * @returns {Date} 目的日期
     */
    DateTool.dateAfterDaysLater = function (beganDate, days) {
        return moment$$1(DateTool.wantDate(beganDate)).add(days, 'days').toDate();
    };
    /**
     * 获取(多态)日期某天后的日期字符串
     * @param {Date | string | number} beganDate 开始日期
     * @param {number} days 天数
     * @param {string} format 格式化信息
     * @returns {string} 目的日期字符串
     */
    DateTool.dateStringAfterDaysLater = function (beganDate, days, format) {
        if (format === void 0) { format = 'YYYY-MM-DD'; }
        return _d2ds(DateTool.dateAfterDaysLater(beganDate, days), format);
    };
    return DateTool;
}());

/* This program is free software. It comes without any warranty, to
     * the extent permitted by applicable law. You can redistribute it
     * and/or modify it under the terms of the Do What The Fuck You Want
     * To Public License, Version 2, as published by Sam Hocevar. See
     * http://www.wtfpl.net/ for more details. */
var leftPad_1 = leftPad;

var cache = [
  '',
  ' ',
  '  ',
  '   ',
  '    ',
  '     ',
  '      ',
  '       ',
  '        ',
  '         '
];

function leftPad (str, len, ch) {
  // convert `str` to a `string`
  str = str + '';
  // `len` is the `pad`'s length now
  len = len - str.length;
  // doesn't need to pad
  if (len <= 0) return str;
  // `ch` defaults to `' '`
  if (!ch && ch !== 0) ch = ' ';
  // convert `ch` to a `string` cuz it could be a number
  ch = ch + '';
  // cache common use cases
  if (ch === ' ' && len < 10) return cache[len] + str;
  // `pad` starts with an empty string
  var pad = '';
  // loop
  while (true) {
    // add `ch` to `pad` if `len` is odd
    if (len & 1) pad += ch;
    // divide `len` by 2, ditch the remainder
    len >>= 1;
    // "double" the `ch` so this operation count grows logarithmically on `len`
    // each time `ch` is "doubled", the `len` would need to be "doubled" too
    // similar to finding a value in binary search tree, hence O(log(n))
    if (len) ch += ch;
    // `len` is 0, exit the loop
    else break;
  }
  // pad `str`!
  return pad + str;
}

/**
 * 数字工具类
 * @memberOf module:tool
 */
var NumberTool = /** @class */ (function () {
    function NumberTool() {
    }
    /**
     * 整数补0
     * @param {number} number 整数
     * @param {number} length 最终的长度
     * @returns {string}  整数字符串
     */
    NumberTool.zeroPad = function (number, length) {
        return leftPad_1(number, length, 0);
    };
    /**
     * 字符补位
     * @param {number | string} pad 字符
     * @param {number} length 最终的长度
     * @param {number, string} placeholder 补全字符
     * @returns {string}  字符串
     */
    NumberTool.leftPad = function (pad, length, placeholder) {
        if (placeholder === void 0) { placeholder = 0; }
        return leftPad_1(pad, length, placeholder);
    };
    /**
     * 小数部分有效数字保留
     * @param {number} number 数字
     * @param {number} digits 小数保留位数
     * @returns {string} 数字的字符串
     */
    NumberTool.fixDigits = function (number, digits) {
        return Number(number).toFixed(digits);
    };
    /**
     * 返回正整数的字符串（非正整数返回指定字符串或空字符串）
     * @param {number} number 数字
     * @param {string} text 非正整数的返回（可空）
     * @returns {string} 正整数字符串或者指定字符串
     */
    NumberTool.positiveText = function (number, text) {
        if (number <= 0) {
            return text || '';
        }
        else {
            return number + '';
        }
    };
    return NumberTool;
}());

/**
 * Created by cuppi on 2016/12/14.
 */
/**
 * 字符串工具类
 * @memberOf module:tool
 */
var StringTool = /** @class */ (function () {
    function StringTool() {
    }
    /**
     * 校验是否为手机号码
     * @param {string} mobile 手机号码
     * @returns {boolean} 结果
     */
    StringTool.isMobile = function (mobile) {
        return (/^1[345789]\d{9}$/.test(mobile));
    };
    /**
     * 校验是否为电话号码
     * @param {string} phone 电话号码
     * @returns {boolean} 结果
     */
    StringTool.isPhoneNumber = function (phone) {
        return /(\(\d{3,4}\)|\d{3,4}-|\s)?\d{7,14}/.test(phone);
    };
    /**
     * 检验是否为邮箱
     * @param {string} email 邮箱
     * @returns {boolean} 结果
     */
    StringTool.isEmail = function (email) {
        return /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/.test(email);
    };
    /**
     * 校验是否为空字符串
     * @param {string} string 字符串
     * @returns {boolean} 结果
     */
    StringTool.isEmpty = function (string) {
        return !(string && string !== '');
    };
    /**
     * 校验是否为验证码（即0~9 6位数字）
     * @param {string} verifycode 验证码
     * @returns {boolean} 结果
     */
    StringTool.isVerifyCode = function (verifycode) {
        return (/^[0-9]{6}$/.test(verifycode));
    };
    /**
     * 校验是否为密码
     * @param {string} password 密码
     * @param {number} minLength 最小长度
     * @param {number} maxLength 最大长度
     * @returns {boolean} 结果
     */
    StringTool.isPassword = function (password, minLength, maxLength) {
        if (minLength !== undefined && maxLength !== undefined) {
            return new RegExp("^[a-zA-Z0-9]{" +
                minLength + "," + maxLength +
                "}$").test(password);
        }
        return (/^[a-zA-Z0-9]{6,14}$/.test(password));
    };
    /**
     * 去除数字左边所有0
     * @param c
     * @returns {*}
     */
    StringTool.numberRemoveLeftZero = function (c) {
        if (/^[0-9]*$/.test(c)) {
            return Number.parseInt(c) + '';
        }
        return c;
    };
    /**
     * 通过asc得出字符数值
     * @param {string} ascChar asc字符
     * @returns {number} 数值 A=0; B=1;
     */
    StringTool.numberFromASC = function (ascChar) {
        var asc = ascChar.charCodeAt(0);
        if (asc >= 65 && asc <= 90) {
            asc -= 65;
        }
        else if (asc >= 97 && asc <= 122) {
            asc -= 97;
        }
        else if (asc >= 48 && asc <= 57) {
            asc -= 48;
        }
        else {
            asc = 0;
        }
        return asc;
    };
    /**
     * 转换字符串到数字
     * @param {string} string 字符串
     * @param {boolean} force 是否强制转换非数字字符 (即为26进制数字)
     * @param {number} offset 非数字时的初始值
     * @returns {number} 数值
     */
    StringTool.numberFromString = function (string, force, offset) {
        if (/^[0-9]*$/.test(string)) {
            return Number.parseInt(string);
        }
        var sum = offset ? offset : 0;
        if (force) {
            for (var i = string.length - 1, radix = 1; i >= 0; i--, radix = radix * 26) {
                sum += StringTool.numberFromASC(string[i]) * radix;
            }
        }
        return sum;
    };
    /**
     * 清除所有空格字符
     * @param {string} string 字符串
     * @returns {string} 结果字符串
     */
    StringTool.clearSpace = function (string) {
        // 过滤空格
        return string.replace(/\s+/g, '');
    };
    /**
     * 清除所有逗号
     * @param {string} string 字符串
     * @returns {string} 结果字符串
     */
    StringTool.clearComma = function (string) {
        // 过滤空格
        return string.replace(/\u002c+/g, '').replace(/，+/g, '');
    };
    /**
     * 清除所有竖线
     * @param {string} string 字符串
     * @returns {string} 结果字符串
     */
    StringTool.clearVertical = function (string) {
        // 过滤空格
        return string.replace(/\|+/g, '');
    };
    /**
     * 清除所有特殊字符
     * @param {string} string 字符串
     * @returns {string} 结果字符串
     */
    StringTool.clearClutter = function (string) {
        var clearString = StringTool.clearSpace(string);
        clearString = StringTool.clearComma(clearString);
        clearString = StringTool.clearVertical(clearString);
        return clearString;
    };
    return StringTool;
}());

/**
 * Created by cuppi on 2016/12/7.
 */
/** @module tool*/
/**
 * 数组工具类
 * @hideconstructor
 */
var ArrayTool = /** @class */ (function () {
    function ArrayTool() {
    }
    return ArrayTool;
}());

/**
 * Created by cuppi on 2017/4/19.
 */
var JSDK = /** @class */ (function () {
    function JSDK() {
    }
    JSDK.version = function () {
        return process.env.NODE_ENV;
    };
    return JSDK;
}());

/**
 * Created by cuppi on 2017/4/14.
 */
/* eslint-enable */

exports.JNetwork = JNetwork;
exports.JNetworkGroup = JNetworkGroup;
exports.JNetworkRoot = JNetworkRoot;
exports.JNetworkError = JNetworkError;
exports.JToolDate = DateTool;
exports.JToolNumber = NumberTool;
exports.JToolUrl = UrlTool;
exports.JToolString = StringTool;
exports.JToolArray = ArrayTool;
exports.JToolObject = ObjectTool;
exports.JSDK = JSDK;
exports.jlink = jlink;
exports.jpara = jpara;
});

unwrapExports(lib);
var lib_1 = lib.JNetwork;
var lib_2 = lib.JNetworkGroup;
var lib_3 = lib.JNetworkRoot;
var lib_4 = lib.JNetworkError;
var lib_5 = lib.JToolDate;
var lib_6 = lib.JToolNumber;
var lib_7 = lib.JToolUrl;
var lib_8 = lib.JToolString;
var lib_9 = lib.JToolArray;
var lib_10 = lib.JToolObject;
var lib_11 = lib.JSDK;
var lib_12 = lib.jlink;
var lib_13 = lib.jpara;

var JNetworkBanner = {
    banners: {
        url: '/banners'
    }
};

var JNetworkCinema = {
    cinemas: {
        url: '/cinema/cinemas',
        bodyData: {
            "filmId": false,
            "date": false,
            "feature": false,
            "limit": false,
            "orderType": false,
            "regionName": false
        },
        useBodyData: [
            'cityId',
            'coordinate'
        ]
    },
    cinemaDetail: {
        url: '/cinema/detail',
        bodyData: {
            cinemaId: true
        }
    },
    cinemaScreeningFilmList: {
        url: '/cinema/films',
        bodyData: {
            cinemaId: true
        }
    },
    cinemaScreeningDateList: {
        url: '/cinema/filmShowDates',
        bodyData: {
            cinemaId: true,
            filmId: true
        },
        cook: function (_a) {
            var data = _a.data;
            return data.map(function (date) {
                return lib_5.timeIntervalFromDateString(date);
            });
        }
    },
    cinemaScreeningItems: {
        url: '/cinema/filmShows',
        bodyData: {
            cinemaId: true,
            date: {
                required: true,
                cook: function (_) { return lib_5.dateStringFromTimeInterval(_, 'yyyy-MM-dd'); }
            },
            filmId: true
        }
    },
    cinemaSeats: {
        url: '/cinema/realTimeSeats',
        bodyData: {
            jbzCinemaId: true,
            platform: true,
            sectionId: false,
            showId: true
        }
    }
};

var RootModel = /** @class */ (function () {
    function RootModel(obj) {
    }
    return RootModel;
}());
var fillProperty = function (self, obj) {
    for (var key in obj) {
        if (obj.hasOwnProperty(key) && self.hasOwnProperty(key)) {
            self[key] = obj[key];
        }
    }
};

var FilmModel = /** @class */ (function (_super) {
    __extends(FilmModel, _super);
    function FilmModel(obj) {
        var _this = _super.call(this, obj) || this;
        _this.actors = null;
        _this.area = null;
        _this.bigImg = null;
        _this.category = null;
        _this.description = null;
        _this.dimensional = null;
        _this.director = null;
        _this.duration = null;
        _this.grade = null;
        _this.hotOrWait = null;
        _this.id = null;
        _this.info = null;
        _this.language = null;
        _this.name = null;
        _this.photos = null;
        _this.show = null;
        _this.showDate = null;
        _this.smallImg = null;
        fillProperty(_this, obj);
        return _this;
    }
    FilmModel.create = function (obj) {
        return new FilmModel(obj);
    };
    return FilmModel;
}(RootModel));

var FilmSimpleModel = /** @class */ (function (_super) {
    __extends(FilmSimpleModel, _super);
    // bdId:string = null;
    // mtimeId:string = null
    // myId:string = null
    // tbId:string = null
    // wpId:string = null
    function FilmSimpleModel(obj) {
        var _this = _super.call(this, obj) || this;
        _this.id = null;
        _this.dimensional = null;
        _this.grade = null;
        _this.name = null;
        _this.show = false;
        _this.smallImg = null;
        fillProperty(_this, obj);
        return _this;
    }
    FilmSimpleModel.create = function (obj) {
        return new FilmSimpleModel(obj);
    };
    return FilmSimpleModel;
}(RootModel));

var CommentModel = /** @class */ (function (_super) {
    __extends(CommentModel, _super);
    // filmId: number = null;
    // source: string = null;
    // platfromId: number = null;
    // spoiler: number = null;
    // sureViewed: string = null;
    // oppose: number = null;
    function CommentModel(obj) {
        var _this = _super.call(this, obj) || this;
        _this.approve = null;
        _this.content = null;
        _this.id = null;
        _this.nick = null;
        _this.score = null;
        _this.time = null;
        fillProperty(_this, obj);
        _this.time = lib_5.timeIntervalFromDateString(_this.time);
        return _this;
    }
    CommentModel.create = function (obj) {
        return new CommentModel(obj);
    };
    return CommentModel;
}(RootModel));

var JNetworkFilm = {
    filmDetail: {
        url: '/film/detail',
        bodyData: {
            filmId: true
        },
        cook: function (data) { return ({
            film: FilmModel.create(data.film),
            comment: data.hotComments.map(function (_) { return CommentModel.create(_); })
        }); }
    },
    filmDetailByPlatform: {
        url: '/film/detailByPartner',
        bodyData: {
            platform: true,
            platformFilmId: true
        },
        cook: function (data) { return FilmModel.create(data); }
    },
    filmDateList: {
        url: '/film/filmDate',
        bodyData: {
            filmId: true
        },
        useBodyData: [
            'cityId'
        ],
        cook: function (data) { return data.map(function (_) { return lib_5.timeIntervalFromDateString(_); }); }
    },
    filmVideo: {
        url: '/film/filmVideo',
        bodyData: {
            filmId: true
        },
        description: '无数据'
    },
    hotComments: {
        url: '/film/hotComments',
        bodyData: {
            filmId: true
        },
        description: '无数据'
    },
    hotfilms: {
        url: '/film/hotFilms',
        cook: function (data) { return data.map(function (_) { return FilmModel.create(_); }); }
    },
    hotFilmsByPage: {
        url: '/film/hotFilmsPage',
        bodyData: {
            page: {
                required: true,
                default: 1
            }
        },
        cook: function (data) { return data.map(function (_) { return FilmModel.create(_); }); },
        description: '系统异常'
    },
    hotFilmsSimple: {
        url: '/film/hotFilmsSimple',
        cook: function (data) { return data.map(function (_) { return FilmSimpleModel.create(_); }); }
    },
    waitFilms: {
        url: '/film/upcomingFilms',
        cook: function (data) { return data.map(function (_) { return FilmModel.create(_); }); }
    },
    waitFilmsByPage: {
        url: '/film/upcomingFilmsPage',
        bodyData: {
            page: {
                required: true,
                default: 1
            }
        },
        descirption: '系统异常'
    }
};

/**
 * 城市模型
 * @memberOf module:model
 */
var CityModel = /** @class */ (function (_super) {
    __extends(CityModel, _super);
    function CityModel(obj) {
        var _this = _super.call(this, obj) || this;
        _this.id = null;
        _this.name = null;
        _this.latin = null;
        fillProperty(_this, obj);
        return _this;
    }
    CityModel.create = function (obj) {
        var city_en = obj.city_en, city_name = obj.city_name, id = obj.id;
        return new CityModel({
            id: id,
            name: city_name,
            latin: city_en
        });
    };
    return CityModel;
}(RootModel));

/**
 * 城市模型
 * @memberOf module:model
 */
var DistrictModel = /** @class */ (function (_super) {
    __extends(DistrictModel, _super);
    function DistrictModel(obj) {
        var _this = _super.call(this, obj) || this;
        _this.id = null;
        _this.name = null;
        fillProperty(_this, obj);
        return _this;
    }
    DistrictModel.create = function (obj) {
        var tails = obj.tails, id = obj.id;
        return new DistrictModel({
            id: id,
            name: tails.Name
        });
    };
    return DistrictModel;
}(RootModel));

var JNetworkLocation = {
    cities: {
        url: '/location/cities',
        cook: function (data) { return data.map(function (_) { return CityModel.create(_); }); }
    },
    city: {
        url: '/location/city',
        useBodyData: [
            'coordinate'
        ],
        cook: function (data) { return CityModel.create(data); }
    },
    cityById: {
        url: '/location/cityById',
        useBodyData: [
            'cityId'
        ],
        cook: function (data) { return CityModel.create(data); }
    },
    districts: {
        url: '/location/districts',
        useBodyData: [
            'cityId'
        ],
        cook: function (data) { return data.map(function (_) { return DistrictModel.create(_); }); }
    },
    hotCities: {
        url: '/location/hotCities',
        cook: function (data) { return data.map(function (_) { return CityModel.create(_); }); }
    }
};

var CinemaModel = /** @class */ (function (_super) {
    __extends(CinemaModel, _super);
    function CinemaModel(obj) {
        var _this = _super.call(this, obj) || this;
        _this.address = null;
        _this.comparedNames = null;
        _this.distance = null;
        _this.id = null;
        _this.minPrice = null;
        _this.name = null;
        fillProperty(_this, obj);
        return _this;
    }
    CinemaModel.create = function (obj) {
        return new CinemaModel(obj);
    };
    return CinemaModel;
}(RootModel));

var JNetworkSearch = {
    hotQuery: {
        url: '/search/hotQuery'
    },
    search: {
        url: '/search/search',
        bodyData: {
            queryStr: true
        },
        useBodyData: [
            'cityId',
            'coordinate'
        ],
        cook: function (data) { return ({
            filmList: data.films.map(function (_) { return FilmModel.create(_); }),
            cinemaList: data.cinemas.map(function (_) { return CinemaModel.create(_); })
        }); },
        description: 'cinema 无数据'
    }
};

var JNetworkOther = {
    decrypt: {
        url: '/system/decrypt',
    },
    encrypt: {
        url: '/system/encrypt',
        params: {
            key: true
        }
    },
    login: {
        url: '/system/login'
    }
};

var DEFAULT_NETWORK_CONFIG = {
    precook: function (_) { return _.data; },
    cook: function (_) { return _; },
    method: 'post',
    url: '',
    params: {},
    headers: {},
    bodyData: {},
    useParams: [],
    useHeaders: [],
    useBodyData: [],
    rule: [1, 0, 2]
};
var JConfig = {
    JNetworkBanner: JNetworkBanner,
    JNetworkCinema: JNetworkCinema,
    JNetworkFilm: JNetworkFilm,
    JNetworkLocation: JNetworkLocation,
    JNetworkSearch: JNetworkSearch,
    JNetworkOther: JNetworkOther
};

var _config = JConfig;
var JNetworkWorker = /** @class */ (function (_super) {
    __extends(JNetworkWorker, _super);
    function JNetworkWorker() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    JNetworkWorker.prototype.fetchRequest = function () {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        return _super.prototype.fetchRequest.apply(this, Array.from(args)).then(function (res) {
            if (!res.data.errorCode) {
                return res.data;
            }
            else {
                throw new Error(res.data.message);
            }
        });
    };
    return JNetworkWorker;
}(lib_1));
var configPicker = function (picker) {
    if (!picker) {
        return;
    }
    if (typeof picker === 'function') {
        _config = picker();
    }
    else if (typeof picker === 'object') {
        _config = picker;
    }
};
var revealNetwork = function (networkClass, networkName, config) {
    if (networkName === void 0) { networkName = networkClass.name; }
    if (!JNetworkWorker.isPrototypeOf(networkClass)) {
        throw new Error(networkName + " is not extends of class JNetworkWorker, please extends class JNetworkWorker");
    }
    var classConfig = config ? config[networkName] : _config[networkName];
    if (!classConfig) {
        if (!config[networkName]) {
            throw new Error("network " + networkName + " not found in config " + JSON.stringify(config));
        }
        else {
            throw new Error("network " + networkName + " not found in default_config");
        }
    }
    var _loop_1 = function (key) {
        if (classConfig.hasOwnProperty(key)) {
            var config_1 = classConfig[key];
            var _a = __assign({}, DEFAULT_NETWORK_CONFIG, config_1), precook_1 = _a.precook, cook_1 = _a.cook, method_1 = _a.method, url_1 = _a.url, rule_1 = _a.rule, params_1 = _a.params, headers_1 = _a.headers, bodyData_1 = _a.bodyData, useParams_1 = _a.useParams, useHeaders_1 = _a.useHeaders, useBodyData_1 = _a.useBodyData;
            if (!Array.isArray(rule_1) || rule_1.length !== 3 || rule_1.some(function (_) { return _ > 2 || _ < 0; })) {
                throw new Error("rule \u53C2\u6570\u51FA\u9519");
            }
            // if (Array.isArray(params)){
            // } else if (typeof params === 'object'){
            // } else {
            // }
            var pickValue_1 = function (refer, from) {
                var r = {};
                for (var key_1 in refer) {
                    if (refer.hasOwnProperty(key_1)) {
                        var referObj = refer[key_1];
                        if (typeof referObj === 'boolean') {
                            var required = referObj;
                            if (required && !from.hasOwnProperty(key_1)) {
                                throw new Error("\u53C2\u6570 " + key_1 + " \u4E3A\u7A7A");
                            }
                            if (from.hasOwnProperty(key_1)) {
                                r[key_1] = from[key_1];
                            }
                        }
                        else if (typeof referObj === 'object') {
                            var required = referObj.required;
                            if (from.hasOwnProperty(key_1)) {
                                r[key_1] = referObj.cook ? referObj.cook(from[key_1]) : from[key_1];
                            }
                            else if (required) {
                                if (referObj.hasOwnProperty('default')) {
                                    r[key_1] = referObj.cook ? referObj.cook(referObj['default']) : referObj['default'];
                                }
                                else {
                                    throw new Error("\u53C2\u6570 " + key_1 + " \u4E3A\u7A7A");
                                }
                            }
                        }
                    }
                }
                return r;
            };
            networkClass.prototype[key] = function () {
                var args = [];
                for (var _i = 0; _i < arguments.length; _i++) {
                    args[_i] = arguments[_i];
                }
                var _a, _b;
                try {
                    params_1 = pickValue_1.call(this, params_1, __assign({}, this.pickInjectParams(), (args[rule_1[0]] || {})));
                    bodyData_1 = pickValue_1.call(this, bodyData_1, __assign({}, this.pickInjectBodyData(), (args[rule_1[1]] || {})));
                    headers_1 = pickValue_1.call(this, headers_1, __assign({}, this.pickInjectHeaders(), (args[rule_1[2]] || {})));
                    return (_a = (_b = this
                        .useParams.apply(this, useParams_1)).useHeaders.apply(_b, useHeaders_1)).useBodyData.apply(_a, useBodyData_1).fetchRequest(method_1, this.baseUrl, url_1, params_1, bodyData_1, headers_1)
                        .then(function (data) { return cook_1(precook_1(data)); });
                }
                catch (e) {
                    return Promise.reject(e);
                }
            };
        }
    };
    for (var key in classConfig) {
        _loop_1(key);
    }
    return networkClass;
};

var JNetworkBanner$1 = /** @class */ (function (_super) {
    __extends(JNetworkBanner, _super);
    function JNetworkBanner() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return JNetworkBanner;
}(JNetworkWorker));
var JNetworkBanner$2 = revealNetwork(JNetworkBanner$1);

/**
 * 影院接口
 * @memberOf module:network
 */
var JNetworkCinema$1 = /** @class */ (function (_super) {
    __extends(JNetworkCinema, _super);
    function JNetworkCinema() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return JNetworkCinema;
}(JNetworkWorker));
var JNetworkCinema$2 = revealNetwork(JNetworkCinema$1);

/**
 * 城市及定位接口
 * @memberOf module:network
 * @hideconstructor
 */
var JNetworkLocation$1 = /** @class */ (function (_super) {
    __extends(JNetworkLocation, _super);
    function JNetworkLocation() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return JNetworkLocation;
}(JNetworkWorker));
var JNetworkLocation$2 = revealNetwork(JNetworkLocation$1);

/**
 * 影片接口
 * @memberOf module:network
 */
var JNetworkFilm$1 = /** @class */ (function (_super) {
    __extends(JNetworkFilm, _super);
    function JNetworkFilm() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return JNetworkFilm;
}(JNetworkWorker));
var JNetworkFilm$2 = revealNetwork(JNetworkFilm$1);

var JNetworkSearch$1 = /** @class */ (function (_super) {
    __extends(JNetworkSearch, _super);
    function JNetworkSearch() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return JNetworkSearch;
}(JNetworkWorker));
var JNetworkSearch$2 = revealNetwork(JNetworkSearch$1);

var JNetworkOther$1 = /** @class */ (function (_super) {
    __extends(JNetworkOther, _super);
    function JNetworkOther() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return JNetworkOther;
}(JNetworkWorker));
var JNetworkOther$2 = revealNetwork(JNetworkOther$1);

/**
 * Created by cuppi on 2017/4/19.
 */
var JSDK = /** @class */ (function () {
    function JSDK() {
    }
    JSDK.version = function () {
        return process.env.NODE_ENV;
    };
    return JSDK;
}());

/**
 * Created by cuppi on 2017/4/14.
 */
/* eslint-enable */

exports.JNetworkBanner = JNetworkBanner$2;
exports.JNetworkCinema = JNetworkCinema$2;
exports.JNetworkLocation = JNetworkLocation$2;
exports.JNetworkFilm = JNetworkFilm$2;
exports.JNetworkSearch = JNetworkSearch$2;
exports.JNetworkOther = JNetworkOther$2;
exports.JNetworkWorker = JNetworkWorker;
exports.revealNetwork = revealNetwork;
exports.configPicker = configPicker;
exports.JSDK = JSDK;
